name: e_tourism
description: "The application called E_Tourism. It contains a list of tourism programmes that are available during a period.  Each tour has one group and one driver."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.0
  shared_preferences: ^2.1.1
  #  flutter_localization: ^0.2.0
  google_fonts: 6.1.0
  easy_localization: ^3.0.5
  dropdown_button2: ^2.3.9
  go_router: ^13.0.0
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1
  ionicons: ^0.2.1
  path: ^1.8.3
  flutter_svg: ^2.0.6
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/
    - assets/icons/
    - assets/